# Generated by Django 3.1.7 on 2021-03-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('BZS', 'BUSINESS SUITE'), ('TNS', 'TWIN SUITE'), ('EXS', 'EXECUTIVE SUITE'), ('SGB', 'SINGLE BED')], max_length=3),
        ),
    ]
